(in-package :autotutor)

(load "Scripts/dom-utils.lisp")
(load "Scripts/scratchpad.lisp")
(load "Scripts/common.lisp")
(load "Scripts/pupil.lisp")
(load "Scripts/teacher.lisp")
(load "Scripts/login.lisp")
(load "Scripts/Lessons/lesson-modules-ne.lisp")
(load "Scripts/Lessons/generator-links.lisp")
(load "Scripts/Lessons/mod-digs-nat.lisp")
(load "Scripts/Lessons/mod-basic-add-nat.lisp")
(load "Scripts/Lessons/mod-basic-sub-nat.lisp")
(load "Scripts/Lessons/mod-position-sys1-nat.lisp")
(load "Scripts/Lessons/mod-sub-position-sys-nat.lisp")
(load "Scripts/Lessons/mod-position-sys2-nat.lisp")
(load "Scripts/Lessons/mod-basic-int.lisp")
(load "Scripts/Lessons/mod-table.lisp")
(load "Scripts/Lessons/mod1-mult.lisp")
(load "Scripts/Lessons/mod2-int.lisp")
(load "Scripts/Lessons/mod2-mult.lisp")
(load "Scripts/Lessons/mod1-div-int.lisp")
(load "Scripts/Lessons/mod2-div-int.lisp")

(setf *scratchpad-script* (scratchpad-script))
